package com.bearded.modules.sensor.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.support.annotation.NonNull;

import com.bearded.modules.sensor.persistence.dao.DaoSession;
import com.bearded.modules.sensor.persistence.dao.LocationEntityDao;
import com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao;
import com.bearded.modules.sensor.persistence.dao.SensorMeasurementSeriesEntityDao;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;

import static com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao.Properties.BinSize;
import static com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao.Properties.EndTimestamp;
import static com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao.Properties.Location_id;
import static com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao.Properties.MedianSensorValue;
import static com.bearded.modules.sensor.persistence.dao.SensorMeasurementEntityDao.Properties.StartTimestamp;
// KEEP INCLUDES END

/**
 * Entity mapped to table SensorMeasurement.
 */
public class SensorMeasurementEntity implements com.bearded.common.persistance.ParseableJson, Comparable<SensorMeasurementEntity> {

    private Long id;
    private long measurement_series_id;
    private Long location_id;
    private float medianSensorValue;
    /**
     * Not-null value.
     */
    private String startTimestamp;
    /**
     * Not-null value.
     */
    private String endTimestamp;
    private short binSize;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient SensorMeasurementEntityDao myDao;

    private SensorMeasurementSeriesEntity sensorMeasurementSeriesEntity;
    private Long sensorMeasurementSeriesEntity__resolvedKey;

    private LocationEntity locationEntity;
    private Long locationEntity__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SensorMeasurementEntity() {
    }

    public SensorMeasurementEntity(Long id) {
        this.id = id;
    }

    public SensorMeasurementEntity(Long id, long measurement_series_id, Long location_id, float medianSensorValue, String startTimestamp, String endTimestamp, short binSize) {
        this.id = id;
        this.measurement_series_id = measurement_series_id;
        this.location_id = location_id;
        this.medianSensorValue = medianSensorValue;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
        this.binSize = binSize;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSensorMeasurementEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMeasurement_series_id() {
        return measurement_series_id;
    }

    public void setMeasurement_series_id(long measurement_series_id) {
        this.measurement_series_id = measurement_series_id;
    }

    public Long getLocation_id() {
        return location_id;
    }

    public void setLocation_id(Long location_id) {
        this.location_id = location_id;
    }

    public float getMedianSensorValue() {
        return medianSensorValue;
    }

    public void setMedianSensorValue(float medianSensorValue) {
        this.medianSensorValue = medianSensorValue;
    }

    /**
     * Not-null value.
     */
    public String getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setStartTimestamp(String startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    /**
     * Not-null value.
     */
    public String getEndTimestamp() {
        return endTimestamp;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setEndTimestamp(String endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    public short getBinSize() {
        return binSize;
    }

    public void setBinSize(short binSize) {
        this.binSize = binSize;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public SensorMeasurementSeriesEntity getSensorMeasurementSeriesEntity() {
        long __key = this.measurement_series_id;
        if (sensorMeasurementSeriesEntity__resolvedKey == null || !sensorMeasurementSeriesEntity__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SensorMeasurementSeriesEntityDao targetDao = daoSession.getSensorMeasurementSeriesEntityDao();
            SensorMeasurementSeriesEntity sensorMeasurementSeriesEntityNew = targetDao.load(__key);
            synchronized (this) {
                sensorMeasurementSeriesEntity = sensorMeasurementSeriesEntityNew;
                sensorMeasurementSeriesEntity__resolvedKey = __key;
            }
        }
        return sensorMeasurementSeriesEntity;
    }

    public void setSensorMeasurementSeriesEntity(SensorMeasurementSeriesEntity sensorMeasurementSeriesEntity) {
        if (sensorMeasurementSeriesEntity == null) {
            throw new DaoException("To-one property 'measurement_series_id' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.sensorMeasurementSeriesEntity = sensorMeasurementSeriesEntity;
            measurement_series_id = sensorMeasurementSeriesEntity.getId();
            sensorMeasurementSeriesEntity__resolvedKey = measurement_series_id;
        }
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public LocationEntity getLocationEntity() {
        Long __key = this.location_id;
        if (locationEntity__resolvedKey == null || !locationEntity__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LocationEntityDao targetDao = daoSession.getLocationEntityDao();
            LocationEntity locationEntityNew = targetDao.load(__key);
            synchronized (this) {
                locationEntity = locationEntityNew;
                locationEntity__resolvedKey = __key;
            }
        }
        return locationEntity;
    }

    public void setLocationEntity(LocationEntity locationEntity) {
        synchronized (this) {
            this.locationEntity = locationEntity;
            location_id = locationEntity == null ? null : locationEntity.getId();
            locationEntity__resolvedKey = location_id;
        }
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    /**
     * {@inheritDoc}
     * NOTE: This implementation compares the two elements comparing its start timestamp.
     */
    @Override
    public int compareTo(@NonNull final SensorMeasurementEntity another) {
        return this.startTimestamp.compareTo(another.startTimestamp);
    }

    /**
     * {@inheritDoc}
     */
    @NonNull
    @Override
    public JsonObject toJsonObject() {
        final JsonObject jsonObject = new JsonObject();
        jsonObject.add(Location_id.name, (getLocationEntity() == null)
                ? null : getLocationEntity().toJsonObject());
        jsonObject.add(StartTimestamp.name, new JsonPrimitive(this.startTimestamp));
        jsonObject.add(EndTimestamp.name, new JsonPrimitive(this.endTimestamp));
        jsonObject.add(MedianSensorValue.name, new JsonPrimitive(this.medianSensorValue));
        jsonObject.add(BinSize.name, new JsonPrimitive(this.binSize));
        return jsonObject;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.toJsonObject().toString();
    }
    // KEEP METHODS END

}
