package com.bearded.modules.sensor.internal.persistence.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.bearded.modules.sensor.internal.domain.LocationEntity;
import com.bearded.modules.sensor.internal.domain.SensorMeasurementEntity;
import com.bearded.modules.sensor.internal.domain.SensorMeasurementSeriesEntity;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table SensorMeasurement.
 */
public class SensorMeasurementEntityDao extends AbstractDao<SensorMeasurementEntity, Long> {

    public static final String TABLENAME = "SensorMeasurement";
    private DaoSession daoSession;

    ;
    private String selectDeep;


    public SensorMeasurementEntityDao(DaoConfig config) {
        super(config);
    }

    public SensorMeasurementEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'SensorMeasurement' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MEASUREMENT_SERIES_ID' INTEGER NOT NULL ," + // 1: measurement_series_id
                "'LOCATION_ID' INTEGER," + // 2: location_id
                "'MEDIAN_SENSOR_VALUE' REAL NOT NULL ," + // 3: medianSensorValue
                "'START_TIMESTAMP' TEXT NOT NULL ," + // 4: startTimestamp
                "'END_TIMESTAMP' TEXT NOT NULL ," + // 5: endTimestamp
                "'BIN_SIZE' INTEGER NOT NULL );"); // 6: binSize
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SensorMeasurement'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, SensorMeasurementEntity entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMeasurement_series_id());

        Long location_id = entity.getLocation_id();
        if (location_id != null) {
            stmt.bindLong(3, location_id);
        }
        stmt.bindDouble(4, entity.getMedianSensorValue());
        stmt.bindString(5, entity.getStartTimestamp());
        stmt.bindString(6, entity.getEndTimestamp());
        stmt.bindLong(7, entity.getBinSize());
    }

    @Override
    protected void attachEntity(SensorMeasurementEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public SensorMeasurementEntity readEntity(Cursor cursor, int offset) {
        SensorMeasurementEntity entity = new SensorMeasurementEntity( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // measurement_series_id
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // location_id
                cursor.getFloat(offset + 3), // medianSensorValue
                cursor.getString(offset + 4), // startTimestamp
                cursor.getString(offset + 5), // endTimestamp
                cursor.getShort(offset + 6) // binSize
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, SensorMeasurementEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeasurement_series_id(cursor.getLong(offset + 1));
        entity.setLocation_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMedianSensorValue(cursor.getFloat(offset + 3));
        entity.setStartTimestamp(cursor.getString(offset + 4));
        entity.setEndTimestamp(cursor.getString(offset + 5));
        entity.setBinSize(cursor.getShort(offset + 6));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(SensorMeasurementEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(SensorMeasurementEntity entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSensorMeasurementSeriesEntityDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLocationEntityDao().getAllColumns());
            builder.append(" FROM SensorMeasurement T");
            builder.append(" LEFT JOIN SensorMeasurementSeries T0 ON T.'MEASUREMENT_SERIES_ID'=T0.'_id'");
            builder.append(" LEFT JOIN Location T1 ON T.'LOCATION_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected SensorMeasurementEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        SensorMeasurementEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SensorMeasurementSeriesEntity sensorMeasurementSeriesEntity = loadCurrentOther(daoSession.getSensorMeasurementSeriesEntityDao(), cursor, offset);
        if (sensorMeasurementSeriesEntity != null) {
            entity.setSensorMeasurementSeriesEntity(sensorMeasurementSeriesEntity);
        }
        offset += daoSession.getSensorMeasurementSeriesEntityDao().getAllColumns().length;

        LocationEntity locationEntity = loadCurrentOther(daoSession.getLocationEntityDao(), cursor, offset);
        entity.setLocationEntity(locationEntity);

        return entity;
    }

    public SensorMeasurementEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString()};
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     */
    public List<SensorMeasurementEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SensorMeasurementEntity> list = new ArrayList<SensorMeasurementEntity>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<SensorMeasurementEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     */
    public List<SensorMeasurementEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

    /**
     * Properties of entity SensorMeasurementEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Measurement_series_id = new Property(1, long.class, "measurement_series_id", false, "MEASUREMENT_SERIES_ID");
        public final static Property Location_id = new Property(2, Long.class, "location_id", false, "LOCATION_ID");
        public final static Property MedianSensorValue = new Property(3, float.class, "medianSensorValue", false, "MEDIAN_SENSOR_VALUE");
        public final static Property StartTimestamp = new Property(4, String.class, "startTimestamp", false, "START_TIMESTAMP");
        public final static Property EndTimestamp = new Property(5, String.class, "endTimestamp", false, "END_TIMESTAMP");
        public final static Property BinSize = new Property(6, short.class, "binSize", false, "BIN_SIZE");
    }

}
