package com.bearded.modules.sensor.internal.persistence.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.bearded.modules.sensor.internal.domain.SensorEntity;
import com.bearded.modules.sensor.internal.domain.SensorMeasurementSeriesEntity;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table SensorMeasurementSeries.
 */
public class SensorMeasurementSeriesEntityDao extends AbstractDao<SensorMeasurementSeriesEntity, Long> {

    public static final String TABLENAME = "SensorMeasurementSeries";
    private DaoSession daoSession;

    ;
    private String selectDeep;


    public SensorMeasurementSeriesEntityDao(DaoConfig config) {
        super(config);
    }

    public SensorMeasurementSeriesEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'SensorMeasurementSeries' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'SENSOR_ID' INTEGER NOT NULL ," + // 1: sensor_id
                "'START_TIMESTAMP' TEXT NOT NULL ," + // 2: startTimestamp
                "'END_TIMESTAMP' TEXT);"); // 3: endTimestamp
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SensorMeasurementSeries'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, SensorMeasurementSeriesEntity entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSensor_id());
        stmt.bindString(3, entity.getStartTimestamp());

        String endTimestamp = entity.getEndTimestamp();
        if (endTimestamp != null) {
            stmt.bindString(4, endTimestamp);
        }
    }

    @Override
    protected void attachEntity(SensorMeasurementSeriesEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public SensorMeasurementSeriesEntity readEntity(Cursor cursor, int offset) {
        SensorMeasurementSeriesEntity entity = new SensorMeasurementSeriesEntity( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // sensor_id
                cursor.getString(offset + 2), // startTimestamp
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // endTimestamp
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, SensorMeasurementSeriesEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSensor_id(cursor.getLong(offset + 1));
        entity.setStartTimestamp(cursor.getString(offset + 2));
        entity.setEndTimestamp(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(SensorMeasurementSeriesEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(SensorMeasurementSeriesEntity entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSensorEntityDao().getAllColumns());
            builder.append(" FROM SensorMeasurementSeries T");
            builder.append(" LEFT JOIN Sensor T0 ON T.'SENSOR_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected SensorMeasurementSeriesEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        SensorMeasurementSeriesEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SensorEntity sensorEntity = loadCurrentOther(daoSession.getSensorEntityDao(), cursor, offset);
        if (sensorEntity != null) {
            entity.setSensorEntity(sensorEntity);
        }

        return entity;
    }

    public SensorMeasurementSeriesEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString()};
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     */
    public List<SensorMeasurementSeriesEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SensorMeasurementSeriesEntity> list = new ArrayList<SensorMeasurementSeriesEntity>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<SensorMeasurementSeriesEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     */
    public List<SensorMeasurementSeriesEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

    /**
     * Properties of entity SensorMeasurementSeriesEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Sensor_id = new Property(1, long.class, "sensor_id", false, "SENSOR_ID");
        public final static Property StartTimestamp = new Property(2, String.class, "startTimestamp", false, "START_TIMESTAMP");
        public final static Property EndTimestamp = new Property(3, String.class, "endTimestamp", false, "END_TIMESTAMP");
    }

}
