package com.bearded.modules.ble.discovery.persistence.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.bearded.modules.ble.discovery.domain.BleDeviceEntity;
import com.bearded.modules.ble.discovery.domain.BleEventSeriesEntity;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table BleEventSeries.
 */
public class BleEventSeriesEntityDao extends AbstractDao<BleEventSeriesEntity, Long> {

    public static final String TABLENAME = "BleEventSeries";
    private DaoSession daoSession;

    ;
    private String selectDeep;


    public BleEventSeriesEntityDao(DaoConfig config) {
        super(config);
    }

    public BleEventSeriesEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'BleEventSeries' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'BLE_DEVICE_ID' INTEGER NOT NULL ," + // 1: bleDeviceId
                "'START_TIMESTAMP' TEXT NOT NULL ," + // 2: startTimestamp
                "'END_TIMESTAMP' TEXT);"); // 3: endTimestamp
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BleEventSeries'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, BleEventSeriesEntity entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBleDeviceId());
        stmt.bindString(3, entity.getStartTimestamp());

        String endTimestamp = entity.getEndTimestamp();
        if (endTimestamp != null) {
            stmt.bindString(4, endTimestamp);
        }
    }

    @Override
    protected void attachEntity(BleEventSeriesEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public BleEventSeriesEntity readEntity(Cursor cursor, int offset) {
        BleEventSeriesEntity entity = new BleEventSeriesEntity( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getLong(offset + 1), // bleDeviceId
                cursor.getString(offset + 2), // startTimestamp
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // endTimestamp
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, BleEventSeriesEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBleDeviceId(cursor.getLong(offset + 1));
        entity.setStartTimestamp(cursor.getString(offset + 2));
        entity.setEndTimestamp(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(BleEventSeriesEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(BleEventSeriesEntity entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBleDeviceEntityDao().getAllColumns());
            builder.append(" FROM BleEventSeries T");
            builder.append(" LEFT JOIN BleDevice T0 ON T.'BLE_DEVICE_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected BleEventSeriesEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        BleEventSeriesEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BleDeviceEntity bleDeviceEntity = loadCurrentOther(daoSession.getBleDeviceEntityDao(), cursor, offset);
        if (bleDeviceEntity != null) {
            entity.setBleDeviceEntity(bleDeviceEntity);
        }

        return entity;
    }

    public BleEventSeriesEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString()};
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /**
     * Reads all available rows from the given cursor and returns a list of new ImageTO objects.
     */
    public List<BleEventSeriesEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BleEventSeriesEntity> list = new ArrayList<BleEventSeriesEntity>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<BleEventSeriesEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

    /**
     * A raw-style query where you can pass any WHERE clause and arguments.
     */
    public List<BleEventSeriesEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

    /**
     * Properties of entity BleEventSeriesEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BleDeviceId = new Property(1, long.class, "bleDeviceId", false, "BLE_DEVICE_ID");
        public final static Property StartTimestamp = new Property(2, String.class, "startTimestamp", false, "START_TIMESTAMP");
        public final static Property EndTimestamp = new Property(3, String.class, "endTimestamp", false, "END_TIMESTAMP");
    }

}
