package com.bearded.modules.ble.discovery.persistence.dao;

import android.database.sqlite.SQLiteDatabase;

import com.bearded.modules.ble.discovery.domain.BleDeviceEntity;
import com.bearded.modules.ble.discovery.domain.BleEventEntity;
import com.bearded.modules.ble.discovery.domain.BleEventSeriesEntity;
import com.bearded.modules.ble.discovery.domain.LocationEntity;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bleDeviceEntityDaoConfig;
    private final DaoConfig bleEventSeriesEntityDaoConfig;
    private final DaoConfig locationEntityDaoConfig;
    private final DaoConfig bleEventEntityDaoConfig;

    private final BleDeviceEntityDao bleDeviceEntityDao;
    private final BleEventSeriesEntityDao bleEventSeriesEntityDao;
    private final LocationEntityDao locationEntityDao;
    private final BleEventEntityDao bleEventEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bleDeviceEntityDaoConfig = daoConfigMap.get(BleDeviceEntityDao.class).clone();
        bleDeviceEntityDaoConfig.initIdentityScope(type);

        bleEventSeriesEntityDaoConfig = daoConfigMap.get(BleEventSeriesEntityDao.class).clone();
        bleEventSeriesEntityDaoConfig.initIdentityScope(type);

        locationEntityDaoConfig = daoConfigMap.get(LocationEntityDao.class).clone();
        locationEntityDaoConfig.initIdentityScope(type);

        bleEventEntityDaoConfig = daoConfigMap.get(BleEventEntityDao.class).clone();
        bleEventEntityDaoConfig.initIdentityScope(type);

        bleDeviceEntityDao = new BleDeviceEntityDao(bleDeviceEntityDaoConfig, this);
        bleEventSeriesEntityDao = new BleEventSeriesEntityDao(bleEventSeriesEntityDaoConfig, this);
        locationEntityDao = new LocationEntityDao(locationEntityDaoConfig, this);
        bleEventEntityDao = new BleEventEntityDao(bleEventEntityDaoConfig, this);

        registerDao(BleDeviceEntity.class, bleDeviceEntityDao);
        registerDao(BleEventSeriesEntity.class, bleEventSeriesEntityDao);
        registerDao(LocationEntity.class, locationEntityDao);
        registerDao(BleEventEntity.class, bleEventEntityDao);
    }

    public void clear() {
        bleDeviceEntityDaoConfig.getIdentityScope().clear();
        bleEventSeriesEntityDaoConfig.getIdentityScope().clear();
        locationEntityDaoConfig.getIdentityScope().clear();
        bleEventEntityDaoConfig.getIdentityScope().clear();
    }

    public BleDeviceEntityDao getBleDeviceEntityDao() {
        return bleDeviceEntityDao;
    }

    public BleEventSeriesEntityDao getBleEventSeriesEntityDao() {
        return bleEventSeriesEntityDao;
    }

    public LocationEntityDao getLocationEntityDao() {
        return locationEntityDao;
    }

    public BleEventEntityDao getBleEventEntityDao() {
        return bleEventEntityDao;
    }

}
