package com.bearded.modules.ble.discovery.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.support.annotation.Nullable;

import com.bearded.modules.ble.discovery.persistence.dao.BleDeviceDao;

import org.json.JSONException;
import org.json.JSONObject;
// KEEP INCLUDES END

/**
 * Entity mapped to table BLE_DEVICE.
 */
public class BleDevice {

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    private Long id;
    /**
     * Not-null value.
     */
    private String deviceAddress;
    private String advertiseName;

    public BleDevice() {
    }

    public BleDevice(Long id) {
        this.id = id;
    }

    public BleDevice(Long id, String deviceAddress, String advertiseName) {
        this.id = id;
        this.deviceAddress = deviceAddress;
        this.advertiseName = advertiseName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getDeviceAddress() {
        return deviceAddress;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDeviceAddress(String deviceAddress) {
        this.deviceAddress = deviceAddress;
    }

    public String getAdvertiseName() {
        return advertiseName;
    }

    public void setAdvertiseName(String advertiseName) {
        this.advertiseName = advertiseName;
    }

    // KEEP METHODS - put your custom methods here
    @Nullable
    private JSONObject toJson() throws JSONException {
        final JSONObject bleDevice = new JSONObject();
        bleDevice.put(BleDeviceDao.Properties.DeviceAddress.name, this.deviceAddress);
        bleDevice.put(BleDeviceDao.Properties.AdvertiseName.name, this.advertiseName);
        return bleDevice;
    }
    // KEEP METHODS END

}
