package com.bearded.modules.ble.discovery.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.support.annotation.NonNull;

import com.bearded.common.database.ParseableJson;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;

import static com.bearded.modules.ble.discovery.persistence.dao.BleDeviceEntityDao.Properties.AdvertiseName;
import static com.bearded.modules.ble.discovery.persistence.dao.BleDeviceEntityDao.Properties.DeviceAddress;
// KEEP INCLUDES END

/**
 * Entity mapped to table BleDevice.
 */
public class BleDeviceEntity implements ParseableJson {

    private Long id;
    /**
     * Not-null value.
     */
    private String deviceAddress;
    private String advertiseName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BleDeviceEntity() {
    }

    public BleDeviceEntity(Long id) {
        this.id = id;
    }

    public BleDeviceEntity(Long id, String deviceAddress, String advertiseName) {
        this.id = id;
        this.deviceAddress = deviceAddress;
        this.advertiseName = advertiseName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getDeviceAddress() {
        return deviceAddress;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDeviceAddress(String deviceAddress) {
        this.deviceAddress = deviceAddress;
    }

    public String getAdvertiseName() {
        return advertiseName;
    }

    public void setAdvertiseName(String advertiseName) {
        this.advertiseName = advertiseName;
    }

    // KEEP METHODS - put your custom methods here

    /**
     * {@inheritDoc}
     */
    @Override
    @NonNull
    public JsonObject toJsonObject() {
        final JsonObject jsonObject = new JsonObject();
        jsonObject.add(DeviceAddress.name, new JsonPrimitive(deviceAddress));
        jsonObject.add(AdvertiseName.name, new JsonPrimitive(advertiseName));
        return jsonObject;
    }
    // KEEP METHODS END

}
