package com.bearded.modules.ble.discovery.domain;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table BLE_EVENT.
 */
public class BleEvent {

    private Long id;
    private Long eventSeriesId;
    /**
     * Not-null value.
     */
    private java.util.Date startTimestamp;
    private java.util.Date endTimestamp;
    private byte receivedSignalStrength;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient BleEventDao myDao;

    private BleEventSeries bleEventSeries;
    private Long bleEventSeries__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BleEvent() {
    }

    public BleEvent(Long id) {
        this.id = id;
    }

    public BleEvent(Long id, Long eventSeriesId, java.util.Date startTimestamp, java.util.Date endTimestamp, byte receivedSignalStrength) {
        this.id = id;
        this.eventSeriesId = eventSeriesId;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
        this.receivedSignalStrength = receivedSignalStrength;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBleEventDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventSeriesId() {
        return eventSeriesId;
    }

    public void setEventSeriesId(Long eventSeriesId) {
        this.eventSeriesId = eventSeriesId;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setStartTimestamp(java.util.Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public java.util.Date getEndTimestamp() {
        return endTimestamp;
    }

    public void setEndTimestamp(java.util.Date endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    public byte getReceivedSignalStrength() {
        return receivedSignalStrength;
    }

    public void setReceivedSignalStrength(byte receivedSignalStrength) {
        this.receivedSignalStrength = receivedSignalStrength;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public BleEventSeries getBleEventSeries() {
        Long __key = this.eventSeriesId;
        if (bleEventSeries__resolvedKey == null || !bleEventSeries__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BleEventSeriesDao targetDao = daoSession.getBleEventSeriesDao();
            BleEventSeries bleEventSeriesNew = targetDao.load(__key);
            synchronized (this) {
                bleEventSeries = bleEventSeriesNew;
                bleEventSeries__resolvedKey = __key;
            }
        }
        return bleEventSeries;
    }

    public void setBleEventSeries(BleEventSeries bleEventSeries) {
        synchronized (this) {
            this.bleEventSeries = bleEventSeries;
            eventSeriesId = bleEventSeries == null ? null : bleEventSeries.getId();
            bleEventSeries__resolvedKey = eventSeriesId;
        }
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
