package com.bearded.modules.ble.discovery.domain;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table BLE_EVENT.
 */
public class BleEvent {

    private Long id;
    private Long bleDevice;
    private Long eventSeries;
    /**
     * Not-null value.
     */
    private java.util.Date startTimestamp;
    private java.util.Date endTimestamp;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient BleEventDao myDao;

    private BleDevice bleDevice;
    private Long bleDevice__resolvedKey;

    private BleEventSeries bleEventSeries;
    private Long bleEventSeries__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BleEvent() {
    }

    public BleEvent(Long id) {
        this.id = id;
    }

    public BleEvent(Long id, Long bleDevice, Long eventSeries, java.util.Date startTimestamp, java.util.Date endTimestamp) {
        this.id = id;
        this.bleDevice = bleDevice;
        this.eventSeries = eventSeries;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBleEventDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBleDevice() {
        return bleDevice;
    }

    public void setBleDevice(Long bleDevice) {
        this.bleDevice = bleDevice;
    }

    public Long getEventSeries() {
        return eventSeries;
    }

    public void setEventSeries(Long eventSeries) {
        this.eventSeries = eventSeries;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setStartTimestamp(java.util.Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public java.util.Date getEndTimestamp() {
        return endTimestamp;
    }

    public void setEndTimestamp(java.util.Date endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public BleDevice getBleDevice() {
        Long __key = this.bleDevice;
        if (bleDevice__resolvedKey == null || !bleDevice__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BleDeviceDao targetDao = daoSession.getBleDeviceDao();
            BleDevice bleDeviceNew = targetDao.load(__key);
            synchronized (this) {
                bleDevice = bleDeviceNew;
                bleDevice__resolvedKey = __key;
            }
        }
        return bleDevice;
    }

    public void setBleDevice(BleDevice bleDevice) {
        synchronized (this) {
            this.bleDevice = bleDevice;
            bleDevice = bleDevice == null ? null : bleDevice.getId();
            bleDevice__resolvedKey = bleDevice;
        }
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public BleEventSeries getBleEventSeries() {
        Long __key = this.eventSeries;
        if (bleEventSeries__resolvedKey == null || !bleEventSeries__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BleEventSeriesDao targetDao = daoSession.getBleEventSeriesDao();
            BleEventSeries bleEventSeriesNew = targetDao.load(__key);
            synchronized (this) {
                bleEventSeries = bleEventSeriesNew;
                bleEventSeries__resolvedKey = __key;
            }
        }
        return bleEventSeries;
    }

    public void setBleEventSeries(BleEventSeries bleEventSeries) {
        synchronized (this) {
            this.bleEventSeries = bleEventSeries;
            eventSeries = bleEventSeries == null ? null : bleEventSeries.getId();
            bleEventSeries__resolvedKey = eventSeries;
        }
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
