package com.bearded.modules.ble.discovery.domain;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table BLE_EVENT_SERIES.
 */
public class BleEventSeriesDao extends AbstractDao<BleEventSeries, Long> {

    public static final String TABLENAME = "BLE_EVENT_SERIES";

    public BleEventSeriesDao(DaoConfig config) {
        super(config);
    }

    ;


    public BleEventSeriesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'BLE_EVENT_SERIES' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'START_TIMESTAMP' INTEGER NOT NULL ," + // 1: startTimestamp
                "'END_TIMESTAMP' INTEGER);"); // 2: endTimestamp
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BLE_EVENT_SERIES'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, BleEventSeries entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStartTimestamp().getTime());

        java.util.Date endTimestamp = entity.getEndTimestamp();
        if (endTimestamp != null) {
            stmt.bindLong(3, endTimestamp.getTime());
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public BleEventSeries readEntity(Cursor cursor, int offset) {
        BleEventSeries entity = new BleEventSeries( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                new java.util.Date(cursor.getLong(offset + 1)), // startTimestamp
                cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)) // endTimestamp
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, BleEventSeries entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStartTimestamp(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setEndTimestamp(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(BleEventSeries entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(BleEventSeries entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity BleEventSeries.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StartTimestamp = new Property(1, java.util.Date.class, "startTimestamp", false, "START_TIMESTAMP");
        public final static Property EndTimestamp = new Property(2, java.util.Date.class, "endTimestamp", false, "END_TIMESTAMP");
    }

}
