package com.bearded.modules.ble.discovery.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BleEventSeries.
 */
public class BleEventSeriesEntity {

    private Long id;
    /** Not-null value. */
    private java.util.Date startTimestamp;
    private java.util.Date endTimestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BleEventSeriesEntity() {
    }

    public BleEventSeriesEntity(Long id) {
        this.id = id;
    }

    public BleEventSeriesEntity(Long id, java.util.Date startTimestamp, java.util.Date endTimestamp) {
        this.id = id;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getStartTimestamp() {
        return startTimestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTimestamp(java.util.Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public java.util.Date getEndTimestamp() {
        return endTimestamp;
    }

    public void setEndTimestamp(java.util.Date endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
