package com.bearded.modules.ble.discovery.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.bearded.modules.ble.discovery.persistence.dao.BleEventEntityDao;
import com.bearded.modules.ble.discovery.persistence.dao.BleEventSeriesEntityDao;
import com.bearded.modules.ble.discovery.persistence.dao.DaoSession;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;

import de.greenrobot.dao.DaoException;

import static com.bearded.common.utils.TimeUtils.timestampToISOString;
import static com.bearded.modules.ble.discovery.persistence.dao.BleEventEntityDao.Properties.StartTimestamp;
import static com.bearded.modules.ble.discovery.persistence.dao.BleEventEntityDao.Properties.EndTimestamp;
import static com.bearded.modules.ble.discovery.persistence.dao.BleEventEntityDao.Properties.ReceivedSignalStrength;

// KEEP INCLUDES END

/**
 * Entity mapped to table BleEvent.
 */
public class BleEventEntity implements com.bearded.common.ParseableJson {

    private Long id;
    private Long eventSeriesId;
    /**
     * Not-null value.
     */
    private java.util.Date startTimestamp;
    private java.util.Date endTimestamp;
    private byte receivedSignalStrength;

    /**
     * Used to resolve relations
     */
    private transient DaoSession daoSession;

    /**
     * Used for active entity operations.
     */
    private transient BleEventEntityDao myDao;

    private BleEventSeriesEntity bleEventSeriesEntity;
    private Long bleEventSeriesEntity__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BleEventEntity() {
    }

    public BleEventEntity(Long id) {
        this.id = id;
    }

    public BleEventEntity(Long id, Long eventSeriesId, java.util.Date startTimestamp, java.util.Date endTimestamp, byte receivedSignalStrength) {
        this.id = id;
        this.eventSeriesId = eventSeriesId;
        this.startTimestamp = startTimestamp;
        this.endTimestamp = endTimestamp;
        this.receivedSignalStrength = receivedSignalStrength;
    }

    /**
     * called by internal mechanisms, do not call yourself.
     */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBleEventEntityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventSeriesId() {
        return eventSeriesId;
    }

    public void setEventSeriesId(Long eventSeriesId) {
        this.eventSeriesId = eventSeriesId;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getStartTimestamp() {
        return startTimestamp;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setStartTimestamp(java.util.Date startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public java.util.Date getEndTimestamp() {
        return endTimestamp;
    }

    public void setEndTimestamp(java.util.Date endTimestamp) {
        this.endTimestamp = endTimestamp;
    }

    public byte getReceivedSignalStrength() {
        return receivedSignalStrength;
    }

    public void setReceivedSignalStrength(byte receivedSignalStrength) {
        this.receivedSignalStrength = receivedSignalStrength;
    }

    /**
     * To-one relationship, resolved on first access.
     */
    public BleEventSeriesEntity getBleEventSeriesEntity() {
        Long __key = this.eventSeriesId;
        if (bleEventSeriesEntity__resolvedKey == null || !bleEventSeriesEntity__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BleEventSeriesEntityDao targetDao = daoSession.getBleEventSeriesEntityDao();
            BleEventSeriesEntity bleEventSeriesEntityNew = targetDao.load(__key);
            synchronized (this) {
                bleEventSeriesEntity = bleEventSeriesEntityNew;
                bleEventSeriesEntity__resolvedKey = __key;
            }
        }
        return bleEventSeriesEntity;
    }

    public void setBleEventSeriesEntity(BleEventSeriesEntity bleEventSeriesEntity) {
        synchronized (this) {
            this.bleEventSeriesEntity = bleEventSeriesEntity;
            eventSeriesId = bleEventSeriesEntity == null ? null : bleEventSeriesEntity.getId();
            bleEventSeriesEntity__resolvedKey = eventSeriesId;
        }
    }

    /**
     * Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context.
     */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context.
     */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context.
     */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    /**
     * {@inheritDoc}
     */
    @Override
    @NonNull
    public JsonObject toJsonObject() {
        final JsonObject bleEvent = new JsonObject();
        bleEvent.add(StartTimestamp.name, getStartTimestampJsonPrimitive());
        bleEvent.add(EndTimestamp.name, getEndTimestampJsonPrimitive());
        bleEvent.add(ReceivedSignalStrength.name, getReceivedSignalStrengthJsonPrimitive());
        return bleEvent;
    }

    @NonNull
    private JsonPrimitive getStartTimestampJsonPrimitive(){
        return new JsonPrimitive(timestampToISOString(this.startTimestamp.getTime()));
    }

    @Nullable
    private JsonPrimitive getEndTimestampJsonPrimitive(){
        if (this.endTimestamp == null){
            return null;
        }
        return new JsonPrimitive(timestampToISOString(this.endTimestamp.getTime()));
    }

    @NonNull
    private JsonPrimitive getReceivedSignalStrengthJsonPrimitive(){
        return new JsonPrimitive(this.receivedSignalStrength);
    }
    // KEEP METHODS END
}
