package com.bearded.modules.ble.discovery.domain;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.bearded.modules.ble.discovery.domain.BleDevice;
import com.bearded.modules.ble.discovery.domain.BleEventSeries;
import com.bearded.modules.ble.discovery.domain.BleEvent;

import com.bearded.modules.ble.discovery.domain.BleDeviceDao;
import com.bearded.modules.ble.discovery.domain.BleEventSeriesDao;
import com.bearded.modules.ble.discovery.domain.BleEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bleDeviceDaoConfig;
    private final DaoConfig bleEventSeriesDaoConfig;
    private final DaoConfig bleEventDaoConfig;

    private final BleDeviceDao bleDeviceDao;
    private final BleEventSeriesDao bleEventSeriesDao;
    private final BleEventDao bleEventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bleDeviceDaoConfig = daoConfigMap.get(BleDeviceDao.class).clone();
        bleDeviceDaoConfig.initIdentityScope(type);

        bleEventSeriesDaoConfig = daoConfigMap.get(BleEventSeriesDao.class).clone();
        bleEventSeriesDaoConfig.initIdentityScope(type);

        bleEventDaoConfig = daoConfigMap.get(BleEventDao.class).clone();
        bleEventDaoConfig.initIdentityScope(type);

        bleDeviceDao = new BleDeviceDao(bleDeviceDaoConfig, this);
        bleEventSeriesDao = new BleEventSeriesDao(bleEventSeriesDaoConfig, this);
        bleEventDao = new BleEventDao(bleEventDaoConfig, this);

        registerDao(BleDevice.class, bleDeviceDao);
        registerDao(BleEventSeries.class, bleEventSeriesDao);
        registerDao(BleEvent.class, bleEventDao);
    }
    
    public void clear() {
        bleDeviceDaoConfig.getIdentityScope().clear();
        bleEventSeriesDaoConfig.getIdentityScope().clear();
        bleEventDaoConfig.getIdentityScope().clear();
    }

    public BleDeviceDao getBleDeviceDao() {
        return bleDeviceDao;
    }

    public BleEventSeriesDao getBleEventSeriesDao() {
        return bleEventSeriesDao;
    }

    public BleEventDao getBleEventDao() {
        return bleEventDao;
    }

}
